project:
  type: website
  output-dir: docs

website:
  title: "Aman"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: ""
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: /cv-aman-desai.pdf  
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd  
      
format:
  html:
    theme: [cosmo, styles.scss]

