---
title: "Research"
---

## Working Papers

- Measuring Income Inequality of Opportunity : Accounting for Dynamic Complementarity          
    + [PDF](/research_content/jae_special_issue_draft.pdf), [Interview](https://stonecenter.gc.cuny.edu/measuring-inequality-of-opportunity-and-the-importance-of-childhood-circumstances/) 

    + **Abstract** : The egalitarian principle of justice attributes life success to two main factors: circumstances beyond an individual's control and personal effort within it. Roemer's equality of opportunity concept proposes compensating individuals for inequalities arising from unequal circumstances. Dynamic complementarity in skill formation suggests that early childhood skill gaps often persist into adulthood, leading to unequal outcomes. Using PSID data, I classify all measurable factors before age 18 (the age of majority) as circumstances, creating sets based on critical childhood stages to account for dynamic complementarity. My findings show that over 40% of total income inequality can be attributed to inequality of opportunity before adulthood. Moreover, nearly one-third of total income inequality stems from circumstances faced by individuals at or before age five. Using only circumstances identified as important through a random forest—a supervised machine learning model—based on permutation-based importance scores, I estimate the lower bound of inequality of opportunity's share in total inequality before the age of majority to be about 31%. These results underscore the importance of considering childhood circumstances when measuring inequality of opportunity. This consideration is crucial for any public policy involving ex-post compensation or ex-ante investment in human capital to equalize opportunities.


- Effects of COVID-19 on the Academic Performance of College Students
    + [PDF](/research_content/covid-draft.pdf)
    
    + **Abstract** : I analyze the impact of the COVID-19 pandemic on undergraduates’  performance in an introductory economics course at a large public university.  One challenge in analyzing student academic outcomes during the pandemic was the explicit change in grading policies by college administrators as well as the implicit adjustment by faculty designed to mitigate the impact of an abrupt shift to online learning amidst the stress and uncertainly associated with the pandemic. To limit the impact of grading policies, I analyze changes in the raw scores on a common final administered to all sections of the course the year before and for four semesters after the spring of 2020.  To limit variation in the difficulty of the exams from before to during the pandemic, I compare student performance on nearly identical questions on the final  exam overtime. Adjusted mean scores on the common final fell by a point  and the probability of answering the qualitatively same question on the final fell, on average, by 1.5 percentage points. Students with lower GPAs were 3.3 percentage points (or 0.02 standard deviations) less likely to answer similar questions correctly relative to students with higher GPAs during the pandemic. Also, the mean probability of answering a nearly identical question before and after suddenly moving to online classes increased by 5.6 percentage points.

## Works in Progress

- Measuring Educational Inequality of Opportunity in the US
