---
title: "Teaching"
---
### Quinnipiac University

- **EC 1001 Principles of Macroeconomics** (Spring 2026)
    + [Sample Syllabus](/teaching_content/EC 112/ec112_04_syllabus.pdf)

- **EC 111 Principles of Microeconomics** (Fall 2025)
    + [Sample Syllabus](/teaching_content/EC 111/ec111_03_course_syllabus.docx)

### Baruch College

- **ECO 1002 Macroeconomics** (Spring 2025, Fall 2024, Spring 2024, Spring 2021, Fall 2021)
    + [Sample Syllabus](/teaching_content/ECO 1002/Macro-Spring-2025-Aman-Desai.pdf)

- **ECO 4000 Statistical Analysis for Economics and Finance** (Summer 2024, Fall 2023, Summer 2023, Spring 2023, Fall 2022, Summer 2022, Spring 2022)
    + [Sample Syllabus](/teaching_content/ECO 4000/ECO_4000_Spring_2022.html)

- **ECO 1110 Current Economic Problems** (Spring 2022, Fall 2021, Spring 2021, Fall 2020, Spring 2020, Fall 2019)
    + [Sample Syllabus](/teaching_content/ECO 1110/ECO_1110_Spring_2022.html)


### Brooklyn College

- **BUSN 3400 Introduction to Economic and Business Statistics** (Spring 2020, Fall 2019)
    + [Sample Syllabus](/teaching_content/BUSN 3400/Syllabus_3400Spring2020.docx)
    